import { AiClient, type EmailDraftRequest } from '../../services/aiClient.js';
import type { ChatClient } from '../../services/chatClient.js';
import { resolveModelConfig } from '../../config/modelCatalog.js';
import { buildChatClientForModel } from '../../services/providers/buildChatClient.js';

export function createDefaultChatClient() {
  const modelConfig = resolveModelConfig({ task: 'draft' });
  try {
    return buildChatClientForModel(modelConfig);
  } catch {
    const chatClient: ChatClient = {
      complete: async (messages) => {
        const last = messages[messages.length - 1];
        let request: EmailDraftRequest | null = null;
        try {
          request = JSON.parse(last.content) as EmailDraftRequest;
        } catch {
          request = null;
        }

        if (request) {
          return JSON.stringify({
            subject: `${request.brief.offer.product_name} for ${request.brief.prospect.company_name}`,
            body: `Hi ${request.brief.prospect.full_name},\n\n${request.brief.offer.one_liner}\n`,
            metadata: {
              model: 'pipeline-express-stub',
              language: request.language,
              pattern_mode: request.pattern_mode,
              email_type: request.email_type,
              coach_prompt_id: 'express_stub',
            },
          });
        }

        const lastUser = [...messages].reverse().find((message) => message.role === 'user');
        const content = lastUser?.content ?? '';
        if (content.includes('ICP profile id:')) {
          return JSON.stringify({ hypothesisLabel: 'Stub Hypothesis', searchConfig: {} });
        }
        if (content.includes('ICP profile name:')) {
          return JSON.stringify({
            name: 'Stub ICP Profile',
            description: 'Stub ICP profile generated by live adapter',
            companyCriteria: {},
            personaCriteria: {},
          });
        }

        return JSON.stringify({
          subject: 'Draft subject',
          body: 'Draft body',
          metadata: {
            model: 'mock-model',
            language: 'en',
            pattern_mode: null,
            email_type: 'intro',
            coach_prompt_id: 'mock',
          },
        });
      },
    };
    return chatClient;
  }
}

export function createAiClient(chatClient?: ChatClient, aiClient?: AiClient) {
  const resolvedChatClient = chatClient ?? createDefaultChatClient();
  return {
    chatClient: resolvedChatClient,
    aiClient: aiClient ?? new AiClient(resolvedChatClient),
  };
}
