import { useEffect, useMemo, useState } from 'react';
import { fetchDrafts, type DraftRow } from '../apiClient';

const translations: Record<string, Record<string, string>> = {
  en: {
    title: 'Bump queue',
    pendingReview: 'Pending review',
    approvedToday: 'Approved today',
    sendable: 'Sendable',
    sent: 'Sent',
    rejected: 'Rejected',
    noBumps: 'No bump drafts',
    selectCampaign: 'Select a campaign',
    autoGenerated: 'Auto-generated',
    approvedTodaySendableTomorrow: 'Approved today — sendable tomorrow',
  },
  ru: {
    title: 'Очередь bump',
    pendingReview: 'Ожидают ревью',
    approvedToday: 'Одобрены сегодня',
    sendable: 'Готовы к отправке',
    sent: 'Отправлены',
    rejected: 'Отклонены',
    noBumps: 'Нет bump-черновиков',
    selectCampaign: 'Выберите кампанию',
    autoGenerated: 'Авто-генерация',
    approvedTodaySendableTomorrow: 'Одобрено сегодня — отправка завтра',
  },
};

function getT(language: string) {
  return translations[language] ?? translations['en'];
}

function isToday(dateStr: string | null | undefined): boolean {
  if (!dateStr) return false;
  const d = new Date(dateStr);
  const now = new Date();
  return d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth() && d.getDate() === now.getDate();
}

function isAutoGenerated(draft: DraftRow): boolean {
  const meta = draft.metadata as Record<string, unknown> | null;
  if (!meta) return false;
  return meta.source === 'auto_bump_generation' || meta.source === 'bump_auto_generate';
}

export interface BumpQueueSummary {
  pendingReview: number;
  approvedToday: number;
  sendable: number;
  sent: number;
  rejected: number;
  total: number;
  hasAutoGenerated: boolean;
}

export function computeBumpSummary(drafts: DraftRow[]): BumpQueueSummary {
  const bumps = drafts.filter((d) => d.email_type === 'bump');
  let pendingReview = 0;
  let approvedToday = 0;
  let sendable = 0;
  let sent = 0;
  let rejected = 0;
  let hasAutoGenerated = false;

  for (const d of bumps) {
    if (isAutoGenerated(d)) hasAutoGenerated = true;

    if (d.status === 'generated') {
      pendingReview += 1;
    } else if (d.status === 'approved') {
      if (isToday(d.updated_at)) {
        approvedToday += 1;
      } else {
        sendable += 1;
      }
    } else if (d.status === 'sent') {
      sent += 1;
    } else if (d.status === 'rejected') {
      rejected += 1;
    }
  }

  return { pendingReview, approvedToday, sendable, sent, rejected, total: bumps.length, hasAutoGenerated };
}

export function CampaignBumpQueueCard({
  campaignId,
  language = 'en',
}: {
  campaignId?: string;
  language?: string;
}) {
  const t = getT(language);
  const [drafts, setDrafts] = useState<DraftRow[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!campaignId) { setDrafts([]); return; }
    let cancelled = false;
    setLoading(true);
    fetchDrafts(campaignId)
      .then((data) => { if (!cancelled) setDrafts(data); })
      .catch(() => {})
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [campaignId]);

  const summary = useMemo(() => computeBumpSummary(drafts), [drafts]);

  if (!campaignId) {
    return (
      <div className="od-context-block" style={{ borderTop: '1px solid var(--od-border)' }}>
        <h3 className="od-context-block__title">{t.title}</h3>
        <span style={{ fontSize: 12, color: 'var(--od-text-muted)' }}>{t.selectCampaign}</span>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="od-context-block" style={{ borderTop: '1px solid var(--od-border)' }}>
        <h3 className="od-context-block__title">{t.title}</h3>
        <span className="od-skeleton" style={{ height: 12, width: '50%' }} />
      </div>
    );
  }

  if (summary.total === 0) {
    return (
      <div className="od-context-block" style={{ borderTop: '1px solid var(--od-border)' }}>
        <h3 className="od-context-block__title">{t.title}</h3>
        <span style={{ fontSize: 12, color: 'var(--od-text-muted)' }}>{t.noBumps}</span>
      </div>
    );
  }

  return (
    <div className="od-context-block" style={{ borderTop: '1px solid var(--od-border)' }}>
      <h3 className="od-context-block__title">
        {t.title}
        {summary.hasAutoGenerated && (
          <span className="od-count-chip" style={{ fontSize: 9, marginLeft: 6, color: 'var(--od-orange)' }}>
            {t.autoGenerated}
          </span>
        )}
      </h3>

      <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
        {summary.pendingReview > 0 && (
          <span className="od-count-chip" style={{ fontSize: 10, color: 'var(--od-warning)' }}>
            {summary.pendingReview} {t.pendingReview.toLowerCase()}
          </span>
        )}
        {summary.approvedToday > 0 && (
          <span className="od-count-chip" style={{ fontSize: 10, color: 'var(--od-orange)' }} title={t.approvedTodaySendableTomorrow}>
            {summary.approvedToday} {t.approvedToday.toLowerCase()}
          </span>
        )}
        {summary.sendable > 0 && (
          <span className="od-count-chip" style={{ fontSize: 10, color: 'var(--od-success)' }}>
            {summary.sendable} {t.sendable.toLowerCase()}
          </span>
        )}
        {summary.sent > 0 && (
          <span className="od-count-chip" style={{ fontSize: 10, color: 'var(--od-text-muted)' }}>
            {summary.sent} {t.sent.toLowerCase()}
          </span>
        )}
        {summary.rejected > 0 && (
          <span className="od-count-chip" style={{ fontSize: 10, color: 'var(--od-error)' }}>
            {summary.rejected} {t.rejected.toLowerCase()}
          </span>
        )}
      </div>

      {summary.approvedToday > 0 && (
        <div style={{ fontSize: 11, color: 'var(--od-orange)', marginTop: 4 }}>
          {t.approvedTodaySendableTomorrow}
        </div>
      )}
    </div>
  );
}
