import { cleanup, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi, beforeEach } from 'vitest';

import { CampaignBumpQueueCard, computeBumpSummary } from './CampaignBumpQueueCard';

vi.mock('../apiClient', () => ({
  fetchDrafts: vi.fn(),
}));

import { fetchDrafts } from '../apiClient';
const mockFetchDrafts = vi.mocked(fetchDrafts);

beforeEach(() => { vi.clearAllMocks(); });
afterEach(() => { cleanup(); });

const today = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();

const mockDrafts = [
  { id: 'd1', email_type: 'bump', status: 'generated', updated_at: today, metadata: { source: 'auto_bump_generation' } },
  { id: 'd2', email_type: 'bump', status: 'approved', updated_at: today, metadata: null },
  { id: 'd3', email_type: 'bump', status: 'approved', updated_at: yesterday, metadata: null },
  { id: 'd4', email_type: 'bump', status: 'sent', updated_at: yesterday, metadata: null },
  { id: 'd5', email_type: 'bump', status: 'rejected', updated_at: today, metadata: null },
  { id: 'd6', email_type: 'intro', status: 'approved', updated_at: today, metadata: null },
] as any[];

describe('computeBumpSummary', () => {
  it('counts bump drafts by state', () => {
    const s = computeBumpSummary(mockDrafts);
    expect(s.total).toBe(5); // excludes intro
    expect(s.pendingReview).toBe(1);
    expect(s.approvedToday).toBe(1);
    expect(s.sendable).toBe(1);
    expect(s.sent).toBe(1);
    expect(s.rejected).toBe(1);
  });

  it('detects auto-generated source', () => {
    const s = computeBumpSummary(mockDrafts);
    expect(s.hasAutoGenerated).toBe(true);
  });

  it('returns zeros for empty list', () => {
    const s = computeBumpSummary([]);
    expect(s.total).toBe(0);
    expect(s.hasAutoGenerated).toBe(false);
  });

  it('returns zeros when only intros', () => {
    const s = computeBumpSummary([mockDrafts[5]]);
    expect(s.total).toBe(0);
  });
});

describe('CampaignBumpQueueCard', () => {
  it('shows placeholder when no campaignId', () => {
    render(<CampaignBumpQueueCard />);
    expect(screen.getByText('Select a campaign')).toBeTruthy();
  });

  it('shows no bumps state', async () => {
    mockFetchDrafts.mockResolvedValue([]);
    render(<CampaignBumpQueueCard campaignId="camp-1" />);
    await waitFor(() => {
      expect(screen.getByText('No bump drafts')).toBeTruthy();
    });
  });

  it('shows bump summary', async () => {
    mockFetchDrafts.mockResolvedValue(mockDrafts);
    render(<CampaignBumpQueueCard campaignId="camp-1" />);
    await waitFor(() => {
      expect(screen.getByText('Bump queue')).toBeTruthy();
    });
    expect(screen.getByText('1 pending review')).toBeTruthy();
    expect(screen.getByText('1 approved today')).toBeTruthy();
    expect(screen.getByText('1 sendable')).toBeTruthy();
    expect(screen.getByText('1 sent')).toBeTruthy();
    expect(screen.getByText('1 rejected')).toBeTruthy();
  });

  it('shows auto-generated badge', async () => {
    mockFetchDrafts.mockResolvedValue(mockDrafts);
    render(<CampaignBumpQueueCard campaignId="camp-1" />);
    await waitFor(() => {
      expect(screen.getByText('Auto-generated')).toBeTruthy();
    });
  });

  it('shows approved today message', async () => {
    mockFetchDrafts.mockResolvedValue(mockDrafts);
    render(<CampaignBumpQueueCard campaignId="camp-1" />);
    await waitFor(() => {
      expect(screen.getByText('Approved today — sendable tomorrow')).toBeTruthy();
    });
  });

  it('renders in Russian', async () => {
    mockFetchDrafts.mockResolvedValue(mockDrafts);
    render(<CampaignBumpQueueCard campaignId="camp-1" language="ru" />);
    await waitFor(() => {
      expect(screen.getByText('Очередь bump')).toBeTruthy();
    });
    expect(screen.getByText('Авто-генерация')).toBeTruthy();
  });
});
